export const FETCH_DATA_OFFERS = "FETCH_DATA_OFFERS";
export const IS_OFFER_LOADING = "IS_OFFER_LOADING";
export const FETCH_USE_CASES = "FETCH_USE_CASES";
export const FETCH_ORG_ROLES = "FETCH_ORG_ROLES";
