name: Veracode create issues
on:
  push:
    branches: [develop, master, main]
  schedule:
    - cron: 15 14 * * 6

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
          SRCCLR_WORKSPACE_SLUG: ${{ secrets.SRCCLR_WORKSPACE_SLUG }}
        uses: lerer/veracode-sca@v1.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: true
          fail-on-cvss: 1
          min-cvss-for-issue: 1

      - run: ls -l
        if: always()

      - run: cat scaResults.json
        if: always()
