name: Veracode upload
on:
  push:
    branches: [develop, master, main]
  schedule:
    - cron: 15 14 * * 6

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.API_TOKEN }}
        uses: lerer/veracode-sca@v1.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false
          fail-on-cvss: 1
